awslabs/aws-jwt-verify

- README.md
*Description of changes:* Add basic usage to top of README, makes it easier to understand the library at first sight
> Add basic usage to top of README

- README.md
*Description of changes:* Added quick link to verify parameters
> Added quick link to verify parameters

- README.md
*Description of changes:* Add jwksUri to the generic IDP examples
> Add jwksUri to the generic IDP examples

- README.md
*Issue #23 
*Description of changes: 
Updated Readme.md (v12 -> v14) to clearly present which versions of NodeJS is supported.
> Corrected the docs to show NodeJS v14+ reliance

- .github/workflows/main.yml
*Description of changes:* Fix GitHub action
> Fix GitHub action

- package-lock.json
- package.json
*Description of changes:* Specify in package.json that we need Node 14 minimum
> Specify node engines

- README.md
- src/https.ts
- src/jwt-rsa.ts
- tests/installation-and-basic-usage/test-script.ts
*Issue #, if available:* N/A (would in fact prevent issues)
*Description of changes:* Mention Node.js 14 and TypeScript 4.0.0 more clearly in docs. Also, corrected spelling of NodeJS to Node.js
> Mention Node.js 14 and TypeScript 4.0.0 more clearly in docs

- tests/cognito/package-lock.json
- tests/cognito/package.json
*Description of changes:* Upgrade VM2 (which is a CDK dependency) to version 3.9.4 by bumping CDK package versions
> Upgrade VM2 version

- README.md
*Description of changes:* Sync README.md with implementation: `group` should be `groups`
> Sync README.md with implementation: group --> groups

- README.md
- src/cognito-verifier.ts
- tests/unit/jwt-rsa.test.ts
*Issue #, if available:* #46
*Description of changes:* Documented how to use the generic RSA verifier with Cognito
> Documented how to use the generic RSA verifier with Cognito

- package-lock.json
- package.json
*Description of changes:* Release v3.1.0
> Release v3.1.0

- README.md
*Description of changes:* Document customization of HTTP options such as response timeout
> Document customization of HTTP options such as response timeout

- README.md
- Update `CloudFront Lambda@Edge` in `Usage Examples`.
- The `CloudFront Lambda@Edge` example was not available as is, so I added more detail.
- Fixed how to get `accessToken`.
- Added `request` variable.
> Update `CloudFront Lambda@Edge` in `Usage Examples`.

- package-lock.json
- tests/cognito/package-lock.json
*Description of changes:* Update dev dependencies
> Update dev dependencies

- src/asn1.ts
- src/node-web-compat-web.ts
*Description of changes:* Fix some small code smells
> Fix some small code smells

- dist-create-package.cjs
- package.json
*Issue #, if available:* #111
*Description of changes:* Add version and package name into lower level package.json
> Version sub package

- README.md
*Description of changes:* Actually mention the right supported algorithms in our docs
> Actually mention the right supported algorithms in our docs

- README.md
*Description of changes:* Mention Node 16 in docs
> Mention Node 16 in docs

- README.md
*Description of changes:* Follow up on #187 to fix some more places in the docs where we had an old list of supported algorithms.
> Fixed mention of algorithms in docs

- package-lock.json
- package.json
*Description of changes:* version bump for npm release
> chore: version bump for npm release

- README.md
*Description of changes:* doc tweak
> docs: tweak ALB docs

- .github/workflows/browser.yml
- .github/workflows/codeguru.yml
- package-lock.json
- package.json
- tests/vite-app/cypress.config.ts
- tests/vite-app/cypress/e2e/forminputs.cy.ts
- tests/vite-app/cypress/support/e2e.js
- tests/vite-app/package-lock.json
- tests/vite-app/package.json
- tests/vite-app/util/package.json
*Description of changes:* Fixes CI failures and warnings
> fix: ui test works again after cypress upgrade
