awslabs/aws-jwt-verify

package-lock.json
package.json
src/jwk.ts
src/jwt-rsa.ts
tests/unit/jwk.test.ts
tests/unit/jwt-rsa.test.ts
tests/unit/test-util.ts

*Issue #, if available:* Fixes #6
-  Consider alg as an optional field on the JWK while validating JWK
-  Evaluate if kty on the JWK is set to RSA
-  If JWK has alg set, then validate that alg set in JWT header matches the alg element of JWK
-  Validate that JWT alg header is set to RS256
-  Update jest version

Update jwk validation logic

---

src/cognito-verifier.ts
src/jwt-rsa.ts
src/typing-util.ts

*Description of changes:* Simplified typings, for better readability and to enable proper tsdoc hints on create calls.
*Impact: This change will have no impact on regular usage of this library (e.g. all usage as explained in README). But, this might be a BREAKING change for TypeScript users, who were explicitly depending on the previous typings.

Simplified typings, for better readability and to enable proper tsdoc hints on create calls

---

README.md
package-lock.json
src/assert.ts
src/cognito-verifier.ts
src/error.ts
src/jwt-model.ts
src/jwt-rsa.ts
src/jwt.ts
tests/import-tests/commonjs.cjs
tests/import-tests/esm.mjs
tests/import-tests/typescript.ts
tests/unit/assert.test.ts
tests/unit/cognito-verifier.test.ts
tests/unit/jwt-rsa.test.ts

*Issue #, if available:* #24
*Description of changes:* Ability to include the raw JWT in thrown errors. Also, instead of a generic `AssertionError` more concrete errors are now thrown (e.g. `CognitoJwtInvalidGroupError`) to make it easier to recognize the concrete error at hand.

Include raw jwt in errors

---

README.md
src/jwk.ts
tests/unit/jwk.test.ts

*Description of changes:* Clean up: removes a test function (`release`) from the public interface

Remove test function from public interface declaration

---

src/error.ts
tests/unit/jwt-rsa.test.ts

*Description of changes:* Ensure rawJwt only includes header and payload, NOT signature

Ensure rawJwt only includes header and payload, NOT signature

---

src/cognito-verifier.ts
src/jwt-rsa.ts
tests/import-tests/typescript.ts

*Issue #, if available:* #40
*Description of changes:* Add exports of important types, so users to define variables separately from the making the `CognitoJwtVerifier.create` call, as requested in #40. [Since changing these types would probably be breaking anyway, as they're return values, I see no reason to not export them and let users use them if they want.]
Usage as follows:
```typescript
import {
CognitoJwtVerifierSingleUserPool,
CognitoJwtVerifier, // Import this from the subnamespace now too, not from the top namespace (!)
} from "aws-jwt-verify/cognito-verifier";
// For the generic type parameter, provide the type of the object 
// that you will pass to the actual `create` call later:
let verifier: CognitoJwtVerifierSingleUserPool<{
userPoolId: string;
tokenUse: "id";
}>;
verifier …
```

Add exports of important types

---

package.json
tests/import-tests/typescript.ts

*Issue #, if available:* #47
*Description of changes:* Use the same set of TypeScript types (from `dist/esm`) for top level (`aws-jwt-verify`) as for subpaths (e.g. `aws-jwt-verify/cognito-verifier`). This prevents TypeScript compile errors due to type mismatches.

Harmonize type paths across CommonJS vs ESM

---

tests/cognito/bootstrap-template.yml
tests/cognito/lib/cognito-stack.ts
tests/cognito/package-lock.json
tests/cognito/package.json

*Description of changes:* Update CDK dependencies

Dependency update

---

src/assert.ts
src/error.ts
src/jwk.ts
src/jwt-rsa.ts
src/node-web-compat-node.ts
src/node-web-compat-web.ts
tests/unit/jwt-rsa.test.ts

*Issue #, if available:* #68
*Description of changes:* Only verify for the JWK at hand, that it is a JWK intended for RSA signatures.
In other words: the complete JWKS may from this change onwards, also comprise non-RSA JWKs (e.g. for elliptic curve signatures). Previously, the inclusion of a non-RSA JWK in the JWKS would throw an error, even if that JWK was not used for the signature verification of the JWT at hand.
So the following (new) unit test now passes, where it would have failed before––because there's non-RSA JWKs in the JWKS, that triggered a JWK validation failure before:
https://github.com/awslabs/aws-jwt-verify/blob/752212b283fa395b6076569f59253f9fbab2d90c/tests/unit/jwt-rsa.test.ts#L104-L132
By submitting this pull request, I confirm that you can use, modify, copy, and …

Only verify for the JWK at hand, that it is a JWK intended for RSA signatures

---

README.md

Fix dead link for Best Practices. Current link shows `The page you were looking for couldn't be found`.
Changed it to `https://datatracker.ietf.org/doc/html/draft-ietf-oauth-jwt-bcp-02#section-3` but not sure if maybe txt version is not preferred.

Update README.md - fix dead link

---

.eslintrc.js
src/node-web-compat-web.ts

- Remove references to window in node-web-compat-web.ts This is a fix for the next.js edge runtime
108
As suggested in the issue thread, references to `window` were removed. `window.setTimeout.bind(window)` was replaced with `setTimeout.bind(undefined)`. This fixed the errors that were previously experienced. 
I suggest to add one or more tests that cover support for next.js edge runtime, since this package is an amazing fit for middleware.

Remove references to window

---

README.md
src/jwt-rsa.ts
src/jwt.ts
tests/unit/cognito-verifier.test.ts
tests/unit/jwt-rsa.test.ts

*Issue #, if available:* #82
*Description of changes:* Document the `decomposeJwt` function

Document decomposeJwt

---

.github/workflows/main.yml

- last PRs are failing on CI build due to npm@latest not compatible with node 14

fix: pin build to npm v9

---

src/jwt-model.ts
src/jwt.ts
tests/unit/jwt-rsa.test.ts

"""
Add `sub` claim to JWT standard fields. It was already defined in [Cognito JWT fields](https://github.com/awslabs/aws-jwt-verify/blob/main/src/jwt-model.ts#L54).
"""

Add sub claim to JWT standard fields

---

src/asn1.ts
tests/unit/asn1.test.ts
tests/unit/https.test.ts

*Issue #, if available:* #154
*Description of changes:* Fixes a bug in the DER encoder of aws-jwt-verify that does not add a leading 0-byte if the MSB (most significant bit) of the public key modulus is 1. In NodeJS this doesn't throw, because OpenSSL is friendly enough (?) to still parse the modulus as a positive number, but in bun it leads to the modulus being parsed as a negative number as @cirospaciari saw. I think that's actually right, because the number is supposed to be encoded in 2's complement per DER spec (https://www.itu.int/ITU-T/studygroups/com17/languages/X.690-0207.pdf#%5B%7B%22num%22%3A41%2C%22gen%22%3A0%7D%2C%7B%22name%22%3A%22FitH%22%7D%2C799%5D).
(Also, had to fix a unit test that suddenly failed on me in Node v20, as the message changed slightly)
By submitting this …

Fix MSB 1 leading to negative modulus in bun

---

src/node-web-compat-web.ts

*Description of changes:* Actually use custom error object

fix: actually use custom error object

---

README.md
src/cognito-verifier.ts
src/jwk.ts
src/jwt-verifier.ts
tests/unit/jwt-verifier.test.ts

*Issue #, if available:* #178
*Description of changes:* Allow creating a JwtVerifier for issuer `null` -- that is needed for non-standard IDPs that do not populate the `iss` claim (in our lib `issuer: null` means "do not check the iss claim")

feat: Allow issuer null

---

README.md

*Description of changes:* The list of supported algorithms was in 3 places, and naturally, not in sync between the three. Fixed that! Just one list now.

chore: fix algorithm list in docs

---

src/cognito-verifier.ts
src/jwt.ts

*Description of changes:* Tweaked regular expressions so that they are compiled only once, and the CUP regular expression is slightly sharper now.

Compile regexp once and optimize CUP regex

---

src/https.ts
tests/vite-app/cypress/e2e/fetcher.cy.ts
tests/vite-app/tsconfig.json

- Fixed `tsc` compile error when tsconfig.json has `"skipLibCheck": false` for a web application
`Type 'Buffer<ArrayBufferLike> | undefined' is not assignable to type 'ArrayBuffer | undefined'.`
- added a Cypress `SimpleFetcher` test

fix: Fetcher interface data type

---

.gitignore
README.md
package.json
src/alb-cache.ts
src/alb-verifier.ts
src/cache.ts
src/error.ts
src/index.ts
src/jwt-model.ts
src/jwt-verifier.ts
src/node-web-compat-node.ts
src/node-web-compat-web.ts
src/node-web-compat.ts
tests/cognito/test/cognito.test.ts
tests/unit/alb-cache.test.ts
tests/unit/alb-verifier.test.ts
tests/unit/cache.test.ts

https://github.com/awslabs/aws-jwt-verify/issues/109
Description of changes:
Proposition for an AwsAlbJwksCache implementation.

Alb jwt verifier

---

src/alb-verifier.ts
tests/unit/alb-verifier.test.ts

This PR extends the AlbJwtVerifier to support AWS GovCloud Application Load Balancer (ALB) ARNs by updating the ARN regex pattern and adding test coverage for GovCloud scenarios.
- Core Change
Updated ALB ARN regex pattern in alb-verifier.ts:
Before: /^arn:(?:aws|aws-cn):elasticloadbalancing:([a-z]{2}-(?:gov-)?[a-z]+-\d{1}):.+$/
After: /^arn:(?:aws|aws-cn|aws-us-gov):elasticloadbalancing:([a-z]{2}-(?:gov-)?[a-z]+-\d{1}):.+$/
Added support for aws-us-gov partition alongside existing aws and aws-cn partitions
- Test Coverage
Added test coverage in tests/unit/alb-verifier.test.ts.

feat: support GovCloud ALB ARNs in AlbJwtVerifier and add related tests
